name: dpress
description: A lightweight express like framework.
version: 0.0.2+alphaAlpha
repository: https://github.com/linkalls/dpress
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test:  ^1.25.8
